[[redirects]]
  from = "/api/geo/*"
  to = "https://geo.api.gouv.fr/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/hubeau/*"
  to = "https://hubeau.eaufrance.fr/:splat"
  status = 200
  force = true
